{% set name = "linux-perf" %}
{% set version = "6.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://cdn.kernel.org/pub/linux/kernel/v{{ version.split(".")[0] }}.x/linux-{{ version }}.tar.xz
  sha256: 3e4d8e561da5703a205ae8d7b2bed6c5c64fc4299eebcbfd20481e63b57d5ee3

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - make
    - flex
    - bison
  host:
    - elfutils
    - binutils
    - libcap
    - libnuma
    - libunwind
    - libzlib
    - openssl
    - xz
    - zlib
    - zstd
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - perf list

about:
  home: https://www.kernel.org
  summary: Performance analysis tools for Linux
  description: |
    Performance counters for Linux are a new kernel-based subsystem that
    provide a framework for all things performance analysis. It covers hardware
    level (CPU/PMU, Performance Monitoring Unit) features and software features
    (software counters, tracepoints) as well.
  license: GPL-2.0-only
  license_file: LICENSES/preferred/GPL-2.0
  doc_url: https://docs.kernel.org/

extra:
  recipe-maintainers:
    - chrisburr
